[package]
name = "micrograd"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
mlp_macro = { path = "./mlp_macro"}
# For examples
kdam = "0.5.2"
petgraph = "0.7.1"
csv = "1.3.1"
poloto = "19.1.2"
rust-mnist = "0.2.0"
