name: main

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5
    - name: Install Rust
      run: |
        rustup toolchain install nightly --profile minimal
        rustup default nightly
    - name: Build Project
      run: cargo build
    - name: Test Project
      run: cargo test
